name: Ignacio Palomo Duarte
highlighter: rouge
description: Blog about design, UX, life and whatever
url: https://palomoduarte.com
title: Ignacio Palomo Duarte
paginate: 8
paginate_path: "/blog/:num"
markdown: kramdown
